/*
 * @dev The vebanny population order is used to sort which character is to be used in a particular order.
 */

export const population_order = [
  'Agent J',
  'Athos',
  'Baker',
  'Banhovah',
  'Banmora',
  'Bannible Lector',
  'Banny Ipkiss',
  'Banny Potter',
  'Banny Stark',
  'Baobhan Sith',
  'Batbanny',
  'Beatrix Kiddo',
  'Blondie',
  'Bronson',
  'Desmond Miles',
  'Diana Banana',
  'Dolly Parton',
  'Dotty Gale',
  'Harleen Quinzel',
  'Jonathan Osterman',
  'Edward Teach',
  'Emmett  “Doc” Brown',
  'Enlil',
  'Farceur',
  'Gautama Buddha',
  'Ivar the Boneless',
  'Jango Fett',
  'Jinx',
  'John Row',
  'Johnny Rotten',
  'Johnny Utah',
  'Legolas',
  'Lestat The Undead',
  'Louise Burns',
  'Mario',
  'Masako Tanaka',
  'Mick Mulligan',
  'Miyamoto Musashi',
  'Musa',
  'Nammu',
  'Naruto',
  'Obiwan Kenobanana',
  'Pamela Anderson',
  'Pharaoh King Banatut',
  'Piers Plowman',
  'Pinkie Pie',
  'Primrose',
  'Prince of Darkness',
  'Princess Leia',
  'Princess Peach Toadstool',
  'Rose Bertin',
  'Sakura Haruno',
  'Smalls',
  'Spider Jerusalem',
  'Spock',
  'Tafari Makonnen',
  'Tamar of Georgia',
  'The Witch of Endor',
  'Tinkerbanny',
  'Wade',
];
