/*
 * @dev The vebanny population order is used to sort which character is to be used in a particular order.
 */

export const population_order = [
  'Nammu',
  'Farceur',
  'Bronson',
  'Utah', // 'Johnny Utah',
  'Musa',
  'Primrose ',
  'Toadstool', // 'Princess Peach Toadstool',
  'Bertin', // 'Rose Bertin',
  'Banmora',
  'Ipkiss', // 'Banny Ipkiss',
  'Row', //'John Row',
  'Dotty', // 'Dotty Gale',
  'Baobhan', // 'Baobhan Sith',
  'Plowman', // 'Piers Plowman',
  'Boneless', // 'Ivar the Boneless',
  'Rotten', // 'Johnny Rotten',
  'Sakura', // 'Sakura Haruno',
  'Smalls',
  'Makonnen', // 'Tafari Makonnen',
  'Mulligan', // 'Mick Mulligan',
  'Bannible', // 'Bannible Lector',
  'Wade',
  'Georgia', // 'Tamar of Georgia',
  'Parton', // 'Dolly Parton',
  'Baker',
  'Athos',
  'Endor', // 'The Witch of Endor',
  'Desmond', // 'Desmond Miles',
  'Banhovah',
  'Pinkie', // 'Pinkie Pie',
  'Edward', // 'Edward Teach',
  'Legolas',
  'Naruto',
  'Pharaoh', // 'Pharaoh King Banatut',
  'Agent', // 'Agent J',
  'Batbanny',
  'Mario',
  'Tanaka', // 'Masako Tanaka',
  'Jango', // 'Jango Fett',
  'Tinkerbanny',
  'Stark', // 'Banny Stark',
  'Emmett', // 'Emmett Brown',
  'Beatrix', // 'Beatrix Kiddo',
  'Louise', // 'Louise Burns',
  'Miyamoto', // 'Miyamoto Musashi',
  'Obiwan', // 'Obiwan Kenobanana',
  'Enlil',
  'Spock',
  'Quinzel', // 'Harleen Quinzel',
  'Pamela', // 'Pamela Anderson',
  'Leia', // 'Princess Leia',
  'Lestat', // 'Lestat The Undead',
  'Jinx',
  'Jerusalem', // 'Spider Jerusalem',
  'Diana', // 'Diana Banana ',
  'Potter', // 'Banny Potter',
  'Darkness', // 'Prince of Darkness',
  'Blondie ',
  'Osterman', // 'Jonathan Osterman',
  'Gautama', // 'Gautama Buddha',
];
