export const TIMEZONE = 'America/Los_Angeles';
export const PROCESS_EXIT_SUCCESS = 0;
export const PROCESS_EXIT_FAILURE = 1;
export const Megabyte = 1024 * 1024;
export const MB = Megabyte;
export const MAX_MEMORY = '2GB';
export const MAX_TIME = 60 * 9;
export const BLANK = '';
export const SPACE = ' ';
